### ISSUE TITLE
Extend @Store property wrapper to allow for optional `receive(on:)` RunLoop scheduler

### ISSUE THREAD

**Issue by wboyd600** [Tiny-Home-Consulting/Dependiject#11]
## Checklist

- [x] I searched the [existing GitHub issues][1] and this hasn't already been requested.

## Problem
Updates to published properties from a background thread for `@Store` variables aren't received on `RunLoop.main` (the main thread). Users can avoid using `DispatchQueue.main.async` or `@MainActor` if the `@Store` property wrapper was updated to receive updates on the main thread.

## Feature Request
Users should be able to publish changes from background threads and be able to update UI from the main thread without additional overhead. If the `@Store` property wrapper was updated to receive events on the main run loop, users can publish changes from any thread without worrying about whether or not they're using `@MainActor` concurrency or `DispatchQueue.main.async`

## Value
Adding this feature as the default configuration will simplify the use of Dependiject with SwiftUI. Developers can publish changes to `@Store` Dependijected services for UI updates without having to do any further thread management.

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

**Comment by bbrk24** [comment]
I can absolutely implement this, but there's a few things I'm not sure of, as a consequence of the fact that we didn't write the original implementation of `@Store`. Namely:

- Currently, the comment at the top of the file says  
  ```swift
  //  Copyright © 2021 QuickBird Studios. All rights reserved.
  //  MIT License
  ```
  Would this still be accurate, or should I change it in some way?
- Since we didn't write it in the first place, and to avoid modifying the file, `@Store` is currently undocumented. While I'm changing the file, should I add documentation?
- For similar reasons, parts of the file do not follow our style guide. Should I fix the styling in the whole file, or just the method(s) I touch?

**Comment by wboyd600** [comment]
Yep, I had a feeling this would be the next question to ask. Looping @noahmehl in.
