### ISSUE TITLE
Add examples for mocking protocols that extend `AnyObservableObject`

### ISSUE THREAD

**Issue by wboyd600** [Tiny-Home-Consulting/Dependiject#7]
## Checklist

- [x] I searched the [existing GitHub issues][1] and this hasn't already been requested.

## Problem

In the example projects, we show how one can mock objects with Mockingbird. But there is no example of how to mock injected dependencies when those dependencies whose protocols conform to `AnyObservableObject`. To mock those objects, one must add extra files to the MockingbirdSupport folder, but the example doesn't show exactly how to do that.

## Feature Request

In both of the example projects, create a situation where one would want to mock a class who implements a protocol that inherits `AnyObservable` object. Mock that class in the test, and add the necessary files to MockingbirdSupport to get it to work. Furtherrmore, note that additional files had to be added to MockingbirdSupport to get the tests to work.

## Value

Dependiject claims to make testing easy, but in certain (common) cases extra support files are needed. Since Mockingbird considers types included in Dependiject as external types, we should be providing an example of how we got Mockingbird to mock our 'external' types.

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

**Comment by bbrk24** [comment]
I've been thinking about this, and while I agree, I'm not sure what the licensing implications would be.

Mockingbird puts [their own license][1] in the MockingbirdSupport folder. This applies to all of the files currently in that folder, but it won't apply if we add to it. I didn't worry about it when we first tried it because it was in a private repository where nobody would see it anyways, but now it starts to matter.

I don't know whether we could put the files we add under our own license or not. The `AnyObservableObject` protocol is from XUI, so the original isn't even under our license. The rest of what we would have to add to MockingbirdSupport is just copy-paste from Combine, so we probably can't claim ownership of that either.

That all being said, Mockingbird didn't create any of the classes and protocols already listed there, so if they can claim those under their license, we can probably claim these under ours? I'm not familiar enough with the licenses to say.

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/blob/master/iOS%2013%20Example/MockingbirdSupport/LICENSE.md

**Comment by wboyd600** [comment]
Thanks for responding Bill. I'll check with Noah to see what he has to say about the licensing.

**Comment by noahmehl** [comment]
@bbrk24 yes, we'll use a header like how we included the XUI work in the pod itself.
